//
//  CellConfingName.swift
//  VsSchoolChimes
//
//  Created by admin on 26/10/24.
//

import Foundation

class CellConfingName {
    
    static let HomePageBottomCell = "BottomCVCell"
    static let HomePageTopCell = "TopCVCell"
    static let ContactUsTVCell = "ContactUsTVCell"
    static let SettingsTableViewCell = "SettingsTableViewCell"
    static let SettingHeaderView = "SettingHeaderView"
    static let NotificationTableViewCell = "NotificationTableViewCell"
    static let ImageCvCell = "ImageCvCell"
    static let FAQTableViewCell = "FAQTableViewCell"
    static let LangTvCellTableViewCell = "LangTvCellTableViewCell"
    static let HistoryTC = "HistoryTC"
    static let TextHistoryTVCell = "TextHistoryTVCell"
    static let ImageShowCVCell = "ImageShowCVCell"
    static let ImagePdfCvCell = "ImagePdfCvCell"
    static let ImagePdfTv = "ImagePdfTv"
    static let RecipientTvCell = "RecipientTvCell"
    static let SideTvcell = "SideTvcell"
    static let Tvcell = "Tvcell"
    static let AssignmentListCTVC = "AssignmentListCTVC"
    static let StudentHistryTVC = "StudentHistryTVC"
    static let MeetingsTVcell = "MeetingsTVcell"
    static let PiechartCVCell = "PiechartCVCell"
    static let AttachmentCVCell = "AttachmentCVCell"
    static let DateCVC = "DateCVC"
    static let ImageTVC = "ImageTVC"
    static let AttendenceTVC = "AttendenceTVC"
    static let VideoTVCell = "VideoTVCell"
    static let LessonPlanTvCell = "LessonPlanTvCell"
    static let ReportStudentTVC = "ReportStudentTVC"
    static let LessonDetailsTVcell = "LessonDetailsTVcell"
    static let SchoolTVCell = "SchoolTVCell"
    static let ParentTVCell = "ParentTVCell"
    static let BanerTableViewCell = "BanerTableViewCell"
    static let RatingTableViewCell = "RatingTableViewCell"
    static let RatingTypeTableViewCell = "RatingTypeTableViewCell"
    static let SuggestionsCollectionViewCell = "SuggestionsCollectionViewCell"
    static let StrengthTvCell = "StrengthTvCell"
    static let AttendenceReportTVCell = "AttendenceReportTVCell"
   
    static let NoticeBoardTvcellTableViewCell = "NoticeBoardTvcellTableViewCell"
    static let HomeWorkTVC = "HomeWorkTVC"
    static let EventTVC = "EventTVC"
    static let SectionCollectionViewCell = "SectionCollectionViewCell"
    static let SectionTvTableViewCell = "SectionTvTableViewCell"
    static let CVIconCollectionViewCell = "CVIconCollectionViewCell"
    static let ClassTableViewCell = "ClassTableViewCell"
    static let deleteTV = "deleteTV"
    static let LocationTableViewCell = "LocationTableViewCell"
    static let DailyCollectionTableViewCell = "DailyCollectionTableViewCell"
    static let DailyCollectionFeeCurrentTableViewCell = "DailyCollectionFeeCurrentTableViewCell"
    static let CheckAviableTvHeader = "CheckAviableTvHeader"
    static let CheckAviableTv = "CheckAviableTv"
    static let SlotsCollectionViewCell = "SlotsCollectionViewCell"
    static let PendingFeeReportTableViewCell = "PendingFeeReportTableViewCell"
    static let PaymentListTableViewCell = "PaymentListTableViewCell"
    static let PunchHistTableViewCell = "PunchHistTableViewCell"
    static let StaffPtmTableViewCell = "StaffPtmTableViewCell"
    static let TimeHeader = "TimeHeader"
    static let cancelTableViewCell = "cancelTableViewCell"
    static let  DataCollectionTvHeaderView = "DataCollectionTvHeaderView"
    static let  DailyCollectionFeePaymentTypeTableViewCell = "DailyCollectionFeePaymentTypeTableViewCell"
    static let  SlotHeader = "SlotHeader"
    static let  SlotHistoryTableViewCell = "SlotHistoryTableViewCell"
    static let  PTMCollectionViewCell = "PTMCollectionViewCell"
    static let  CalendarCollectionViewCell = "CalendarCollectionViewCell"
    static let  MessageFromManagementTableViewCell = "MessageFromManagementTableViewCell"
    static let  ClassTimeTableTableViewCell = "ClassTimeTableTableViewCell"
    static let  WeekDaysNameCollectionViewCell = "WeekDaysNameCollectionViewCell"

    static let  ExamsListTVCell = "ExamsListTVCell"
    static let  ExamsListCVCell = "ExamsListCVCell"
    static let  ChatTVCell = "ChatTVCell"
    static let  HomeworkreportTV = "HomeworkreportTV"
    static let  SubscriptionTVCell = "SubscriptionTVCell"
    static let  CertificateTableViewCell = "CertificateTableViewCell"
    static let  LeveHistoryTV = "LeveHistoryTV"
    static let  SenderLeaveTV = "SenderLeaveTV"
    static let  ReciverAttendReportTV = "ReciverAttendReportTV"
    static let  ReciverHomeworkHeader = "ReciverHomeworkHeader"
    static let  ExamMarkTV = "ExamMarkTV"
    static let  ExammarkFooterView = "ExammarkFooterView"
    static let  ExamMarkCV = "ExamMarkCV"
    static let  MarkTvCell = "MarkTvCell"
    static let  addCvCell = "addCvCell"
    static let  seeMore = "seeMore"
    static let  SpecificStudentTvcell = "SpecificStudentTvcell"
    static let  ChatCvcell = "ChatCvcell"
    static let  TimetableTv = "TimetableTv"
    static let  QuizTVcell = "QuizTVcell"
    static let  CompletedTVcell = "CompletedTVcell"
    static let  QuizListTvCell = "QuizListTvCell"
    static let  TakeReadingSkillTableViewCell = "TakeReadingSkillTableViewCell"
    static let  LessonDashboardTv = "LessonDashboardTv"
    static let  LessonProgressCell = "LessonProgressCell"
    static let  SchoolListTVC = "SchoolListTVC"
    static let  cell1Tv = "cell1Tv"
    static let  cell2Tv = "cell2Tv"
    static let  Std_Grp_header = "Std_Grp_header"
    static let  SeeMoreFooterView = "SeeMoreFooterView"
    static let  FiltersCvCell = "FiltersCvCell"
    static let  TAttacmentTVC = "TAttacmentTVC"
    static let  MarkAtendenceTV = "MarkAtendenceTV"
    static let  StudentTVCell = "StudentTVCell"
    static let  LessonViewTvCell = "LessonViewTvCell"
   
    
}
